export class Business{
    idBusiness!:String;
    companyName!:String;
    email!:String;
    password!:String
    active!:boolean
    enabled!:boolean;
    website!:String;
    nbEmployee!:number;
    firstName!:String;
    lastName!:String;
    recrutementRole!:String;
    phone!:String;
    industry!:String;
    country!:String;
    address!:String;
    logo!:String;
    description!:String;
    creationDate!:Date;
}
